# This is the error patten used to distinguage user error and system error
# We collect such info from user log/runtime log and user exit code, and user
# This spec to generate aggregated error

# [200, 219] reserved by FC

- patterns:
  - exitCode: 1
    userLogRegex: exec\(compile\(getattr\(token[a-z]*, 'open', open\)\(__file__\)
  containerExitCode: 10

- patterns:
  - exitCode: 1
    userLogRegex: failed with error code 1 in /tmp/[a-z]*
  - exitCode: 1
    userLogRegex: package not find [a-z]*
  containerExitCode: 12

- patterns:
  - exitCode: 1
    userLogRegex: connect tensorboard failed
    platformLogRegex: Failed to start tensorboard
  containerExitCode: 15

- patterns:
  - exitCode: 137
  containerExitCode: 137

- patterns:
  - exitCode: 143
  containerExitCode: 143